### PR TITLE
Reattempt connection to altimeter at 10hz instead of 100hz

### PR DESCRIPTION
**Pull request by aftersomemath**
No need to check at 100hz. Also if accidentally launched from the desktop it spams the terminal more than necessary.

### CODE REVIEW

**Comment by amiller27** [comment]
This sounds like a "tmux is making things slow when I have lots of output" problem more than an actual problem. I don't see a reason to slow this down, it isn't pegging any resources at 100Hz and its update rate is faster than 10Hz (pretty sure about that but not positive), so reconnecting faster does benefit us.  Really, we could do an increasing delay between attempts, but that's probably not worth our time.

**Comment by aftersomemath** [comment]
Yes it was triggered by tmux not letting me ctr+c out.

I don't think it's good practice to make unreadable (spammed) logs either. See the latest commit.

**Comment by amiller27** [comment]
I like it. I'm assuming this hasn't been tested?

**Comment by aftersomemath** [comment]
Nope. So it will have to sit till after break.

**Comment by aftersomemath** [comment]
This has been tested. Ready to merge IMO.

**Review by amiller27 — APPROVED** [review]

**Pull request merged**
